// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvomqapkzsjijkjnlvis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2b21xYXBrenNqaWpram5sdmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjM0NzIsImV4cCI6MjA2NTQ5OTQ3Mn0.f33NGG_mjgT-5LbdkUFoHfDBWXxwty0wdfj7SwaXqMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);